# Generated by Django 5.1.4 on 2025-01-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('Temperature', 'Temperature'), ('Humidity', 'Humidity'), ('Motion', 'Motion')], max_length=50),
        ),
    ]
