# Generated by Django 5.1.4 on 2025-01-23 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sensordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.device'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
